export const cardsInfo = [
    {
        id: 0,
        name: "Countify",
        description: `<em>Counter</em> developed using
        <strong>Vanilla JavaScript</strong>. We explore the utilization of the <code>addEventListener</code> method to respond to events, specifically the <code>click</code> event.`,
        image: "./assets/counter.webp",
        url: "./01-counterApp/index.html",
        category: "beginner",
    },
    {
        id: 1,
        name: "Slider v.001",
        description: `<em>Slider</em> developed using <strong>Vanilla JavaScript</strong>. In this project we learn how to <code>import</code> data from an external file and how we can insert this data into the <strong>DOM</strong> using the <code>textContent</code> property.`,
        image: "./assets/slider1.webp",
        url: "./02-slider-1/index.html",
        category: "beginner",
    },
    {
        id: 2,
        name: "Password Generator",
        description: `Developed using <strong>Vanilla JavaScript</strong>. In this project we learn how to use the <code>Math.random()</code> method to generate random numbers and how to deal with <code>input</code> values like <code>range</code> and <code>checkbox</code>.`,
        image: "./assets/pass-gen.webp",
        url: "./03-passGen/index.html",
        category: "intermediate",
    },
    {
        id: 3,
        name: "Gradient Generator",
        description: `Developed using <strong>Vanilla JavaScript</strong>. In this project we learn how to use the <code>linear-gradient</code> property to create a gradient background and how to use the <code>input</code> event to update the gradient background in real time.`,
        image: "./assets/gradient-gen.webp",
        url: "./04-gradientGen/index.html",
        category: "intermediate",
    },
    {
        id: 4,
        name: "To-Do App",
        description: `<em>To-Do App</em> developed using <strong>Vanilla JavaScript</strong>. In this project we learn how to use the <code>localStorage</code> method to store and retrieve data from the browser. We also learn how to use <code>matches</code>, <code>closest</code> and <code>contains</code> methods to respond to events.`,
        image: "./assets/todo.webp",
        url: "./05-todoApp/index.html",
        category: "intermediate",
    },
    {
        id: 5,
        name: "Countdown Timer",
        description: `<em>Countdown Timer</em> developed using <strong>Vanilla JavaScript</strong>. In this project we learn how to get the current date and time using the <code>Date()</code> object and how to use the <code>setInterval</code> and <code>setTimeout</code> method to update the <strong>DOM</strong> every second.`,
        image: "./assets/countdown.webp",
        url: "./06-countdownTimer/index.html",
        category: "beginner",
    },
    {
        id: 6,
        name: "Cookie Policy",
        description: `Developed using <strong>Vanilla JavaScript</strong>. In this project we learn how to use the <code>document.cookie</code> property to store and retrieve data from the browser. We also continue to explore the <code>localStorage</code> method.`,
        image: "./assets/cookiesPolicy.webp",
        url: "./07-cookiePolicy/index.html",
        category: "intermediate",
    },
    {
        id: 7,
        name: "Words Counter Pro",
        description: `This <em>Word Counter</em> is a comprehensive implementation using only <strong>Vanilla JavaScript</strong>. We explore updating various properties of multiple DOM elements simultaneously whenever the user inputs text into the <code>textarea</code>.`,
        image: "./assets/words-counter-pro.webp",
        url: "./08-wordsCounter/index.html",
        category: "advanced",
    },
    {
        id: 8,
        name: "BMI Calculator",
        description: `Developed using <strong>Vanilla JavaScript</strong>. In this project we learn how to use the <code>parseInt</code> and <code>parseFloat</code> methods to convert strings to numbers and how to use the <code>toFixed</code> method to round numbers to a specific number of decimal places.`,
        image: "./assets/bmiCalc.webp",
        url: "./09-bmiCalc/index.html",
        category: "beginner",
    },
    {
        id: 9,
        name: "Stopwatch",
        description: `This <strong>JavaScript</strong> code creates a countdown timer with start, stop, and reset buttons using vanilla JavaScript. The <code>updateTimer() </code>function updates the display every second via <code>setInterval()</code>. User interactions trigger <code>start()</code>, <code>stop()</code>, and <code>reset()</code> functions to control the timer.
        `,
        image: "./assets/stopwatch.webp",
        url: "./10-stopwatch/index.html",
        category: "beginner",
    },
    {
        id: 10,
        name: "Weather API",
        description: `Developed using <strong>Vanilla JavaScript</strong>. In this project we learn how to use the <code>fetch()</code> and solve <code>Promises</code> methods to <code>GET</code> some information that we are available from an outside API and render them in our page.`,
        image: "./assets/weather-api.webp",
        url: "./11-weatherApi/index.html",
        category: "intermediate",
    },
    {
        id: 11,
        name: "Virtual Drum",
        description: `Developed using <strong>Vanilla JavaScript</strong>. In this project we learn how to use the <code>audio</code> tag and <code>kbd</code> to play sounds and how to use the <code>keydown</code> event to respond to keyboard events. We also learn how to use the <code>play()</code> methods to play sounds.`,
        image: "https://bit.ly/43NCueY",
        url: "./12-virtualDrum/index.html",
        category: "advanced",
    },
    {
        id: 12,
        name: "Dark Mode",
        description: `Developed using <strong>Vanilla JavaScript</strong>. `,
        image: "https://bit.ly/4aQPT8I",
        url: "./13-darkMode/index.html",
        category: "beginner",
    }
];
