const argentinaPlayers = [
    {
        id: 1,
        name: "Lionel Messi",
        position: "Forward",
        img: "https://bit.ly/4aFF6Pg",
        text: "Considered one of the greatest football players of all time, Messi is known for his incredible dribbling and goal-scoring abilities.",
    },
    {
        id: 2,
        name: "Angel Di Maria",
        position: "Midfielder",
        img: "https://bit.ly/3THTHDR",
        text: "Di Maria is a skilled winger known for his speed and playmaking abilities, often contributing crucial assists to his team.",
    },
    {
        id: 3,
        name: "Emiliano Martinez",
        position: "Goalkeeper",
        img: "https://bit.ly/41JoAcU",
        text: "Martinez is a talented goalkeeper known for his shot-stopping skills and commanding presence in the penalty area.",
    },
    {
        id: 4,
        name: "Nicolas Otamendi",
        position: "Defender",
        img: "https://bit.ly/48CuBdN",
        text: "Otamendi is a solid defender with good aerial ability and a tough-tackling style of play.",
    },
    {
        id: 5,
        name: "Julian Alvarez",
        position: "Forward",
        img: "https://bit.ly/3tDB8WM",
        text: "Alvarez is a versatile forward with a keen eye for goal and the ability to create scoring opportunities for his teammates.",
    },
    {
        id: 6,
        name: "Enzo Fernandez",
        position: "Midfielder",
        img: "https://bit.ly/3TIXq3R",
        text: "Fernandez is a dynamic midfielder known for his passing accuracy and ball control in the middle of the pitch.",
    },
    {
        id: 7,
        name: "Gonzalo Montiel",
        position: "Defender",
        img: "https://bit.ly/48iw8pH",
        text: "Montiel is an energetic full-back known for his overlapping runs and defensive contributions.",
    },
    {
        id: 8,
        name: "Nahuel Molina",
        position: "Defender",
        img: "https://bit.ly/48FokxT",
        text: "Molina is a promising young defender known for his speed and ability to contribute offensively from the right-back position.",
    },
    {
        id: 9,
        name: "Lautaro Martinez",
        position: "Forward",
        img: "https://bit.ly/48iwbln",
        text: "Lautaro Martinez is a striker with a clinical finish, known for his goal-scoring prowess and work rate on the pitch.",
    },
    {
        id: 10,
        name: "Leandro Paredes",
        position: "Midfielder",
        img: "https://bit.ly/48k5aOm",
        text: "Paredez is a strong and reliable Midfielder known for his defensive awareness and ability to read the game.",
    },
    {
        id: 11,
        name: "Exequiel Palacios",
        position: "Midfielder",
        img: "https://bit.ly/41N6zuw",
        text: "Palacios is a talented midfielder with excellent passing ability and vision, contributing both defensively and offensively.",
    },
    {
        id: 12,
        name: "Alexis Mac Allister",
        position: "Midfielder",
        img: "https://bit.ly/41HrHSJ",
        text: "Mac Allister is a creative midfielder known for his dribbling skills and ability to unlock opposing defenses.",
    },
    {
        id: 13,
        name: "Paulo Dybala",
        position: "Forward",
        img: "https://bit.ly/3S58lnh",
        text: "Dybala is a skillful forward with a flair for scoring spectacular goals, often showcasing his technical brilliance on the pitch.",
    },
    {
        id: 14,
        name: "Sergio Aguero",
        position: "Forward",
        img: "https://bit.ly/3tEmTkm",
        text: "Aguero is a prolific striker and goal-scorer with a proven track record of success at both the club and international levels.",
    },
    {
        id: 15,
        name: "Marcos Acuña",
        position: "Midfielder",
        img: "https://bit.ly/3vngnPL",
        text: "Acuña is a versatile midfielder who can play in various positions, known for his work ethic and defensive contributions.",
    },
    {
        id: 16,
        name: "Guido Rodriguez",
        position: "Midfielder",
        img: "https://bit.ly/48kgslw",
        text: "Rodriguez is a strong defensive midfielder known for his ball-winning abilities and ability to shield the defense.",
    },
    {
        id: 17,
        name: "Lucas Ocampos",
        position: "Forward",
        img: "https://bit.ly/47gOENO",
        text: "Ocampos is an agile and versatile forward capable of playing on the wing, known for his pace and goal-scoring prowess.",
    },
    {
        id: 18,
        name: "Giovani Lo Celso",
        position: "Midfielder",
        img: "https://bit.ly/3NLmZxB",
        text: "Lo Celso is a creative midfielder with excellent passing range and vision, known for his ability to dictate play in the midfield.",
    },
    {
        id: 19,
        name: "Cristian Romero",
        position: "Defender",
        img: "https://bit.ly/3vt3zqK",
        text: "Romero is a talented center-back known for his defensive solidity and ability to read the game, making him a key presence in the backline.",
    },
    {
        id: 20,
        name: "Franco Armani",
        position: "Goalkeeper",
        img: "https://bit.ly/47m0QN9",
        text: "Armani is a reliable goalkeeper known for his shot-stopping skills and ability to command the penalty area.",
    },
    {
        id: 21,
        name: "Juan Foyth",
        position: "Defender",
        img: "https://bit.ly/48lmp1C",
        text: "Foyth is a versatile defender capable of playing as a center-back or right-back, known for his composure on the ball and defensive awareness.",
    },
    {
        id: 22,
        name: "Lisandro Martinez",
        position: "Defender",
        img: "https://bit.ly/3S51DxC",
        text: "Martinez is a young and skillful defender known for his ability to play out from the back and make crucial interceptions.",
    },
    {
        id: 23,
        name: "Nicolas Tagliafico",
        position: "Defender",
        img: "https://bit.ly/3tBOaUJ",
        text: "Tagliafico is an energetic left-back known for his attacking contributions and defensive solidity.",
    },
    {
        id: 24,
        name: "German Pezzella",
        position: "Defender",
        img: "https://bit.ly/41OAsdF",
        text: "Pezzella is a reliable center-back known for his leadership qualities and aerial prowess in both defensive and offensive situations.",
    },
    {
        id: 25,
        name: "Rodrigo De Paul",
        position: "Midfielder",
        img: "https://bit.ly/3viEyP7",
        text: "De Paul is a creative midfielder with excellent passing and dribbling skills, contributing both defensively and offensively.",
    },
    {
        id: 26,
        name: "Geronimo Rulli",
        position: "Goalkeeper",
        img: "https://bit.ly/3TJRFTC",
        text: "Rulli is a talented goalkeeper known for his shot-stopping abilities and commanding presence in the penalty area.",
    },
    {
        id: 27,
        name: "Angel Correa",
        position: "Forward",
        img: "https://bit.ly/3TOhli8",
        text: "Correa is a versatile forward known for his speed, technical ability, and goal-scoring prowess.",
    },
    
    {
        id: 28,
        name: "Lionel Scaloni",
        position: "Manager",
        img: "https://bit.ly/3vosxrx",
        text: "Lionel Scaloni is the head coach of the Argentina National Team. As a former footballer, Scaloni brings tactical acumen and leadership to guide the team.",
    },
];

export default argentinaPlayers;
